from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from app.config import OUTPUT_DIR
from app.types import WorkflowResult


def _slugify(value: str) -> str:
    safe = "".join(ch.lower() if ch.isalnum() else "_" for ch in value)
    while "__" in safe:
        safe = safe.replace("__", "_")
    return safe.strip("_")[:60] or "1ove_output"


def render_markdown(result: WorkflowResult) -> str:
    final = result.final_content
    review_lines = []
    for review in result.review_outputs:
        review_lines.append(f"- **{review.reviewer_name}** — {review.status} ({review.score}/5): {'; '.join(review.notes)}")

    voiceover = "\n".join(f"- {line}" for line in final.get("voiceover_script", []))
    visuals = "\n".join(
        f"- **{scene.get('time')}** — {scene.get('visual')}"
        for scene in final.get("visual_direction", [])
    )
    memory_lines = "\n".join(f"- {m.get('title')} [{m.get('tier')}]" for m in result.memory_context) or "- No memory context used."

    eval_lines = "\n".join(f"- {k}: {v}" for k, v in result.evaluation.category_scores.items())

    return f"""# {final.get('title')}

## Stage 13 Decision
**{result.evaluation.decision}** — {result.evaluation.total_score}/{result.evaluation.max_score}

## Memory Context Used
{memory_lines}

## Platform
{final.get('platform')}

## Duration
{final.get('duration')}

## Hook
{final.get('hook')}

## Voiceover Script
{voiceover}

## Scene-by-Scene Visual Direction
{visuals}

## Music Mood
{final.get('music_mood')}

## Subtitle Style
{final.get('subtitle_style')}

## Editing Style
{final.get('editing_style')}

## Ending Line
{final.get('ending_line')}

## Call to Action
{final.get('call_to_action')}

## Review Notes
{chr(10).join(review_lines)}

## Evaluation Scorecard
{eval_lines}

## Issues
{chr(10).join('- ' + issue for issue in result.evaluation.issues) or '- None'}

## Final Video Prompt
{final.get('final_video_prompt')}

---
Generated by 1oVE Creative OS v1 — Stage 13 Full Local Runner v1.
"""


def write_outputs(result: WorkflowResult, output_path: Path | None = None) -> Path:
    OUTPUT_DIR.mkdir(exist_ok=True)

    if output_path is None:
        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        title = _slugify(result.final_content.get("title", "1ove_output"))
        output_path = OUTPUT_DIR / f"{stamp}_{title}.md"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_markdown(result), encoding="utf-8")

    json_path = output_path.with_suffix(".json")
    json_payload = {
        "brief": {
            "idea": result.brief.idea,
            "platform": result.brief.platform,
            "duration": result.brief.duration,
            "privacy_mode": result.brief.privacy_mode,
            "use_memory": result.brief.use_memory,
        },
        "privacy_hits": result.privacy_hits,
        "memory_context": result.memory_context,
        "agent_outputs": [
            {"agent_name": item.agent_name, "content": item.content}
            for item in result.agent_outputs
        ],
        "review_outputs": [
            {"reviewer_name": item.reviewer_name, "status": item.status, "score": item.score, "notes": item.notes}
            for item in result.review_outputs
        ],
        "evaluation": {
            "decision": result.evaluation.decision,
            "total_score": result.evaluation.total_score,
            "max_score": result.evaluation.max_score,
            "category_scores": result.evaluation.category_scores,
            "issues": result.evaluation.issues,
        },
        "final_content": result.final_content,
    }
    json_path.write_text(json.dumps(json_payload, indent=2, ensure_ascii=False), encoding="utf-8")

    eval_path = output_path.with_suffix(".scorecard.json")
    eval_path.write_text(json.dumps(json_payload["evaluation"], indent=2, ensure_ascii=False), encoding="utf-8")

    return output_path
